defconfig: add missing rk808 regulator options
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG rk_iodomain_probe:121 reg:pmuio1
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:211 reg:pmuio1
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:217
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:231 prop:pmuio1-supply
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:243
rk808 rk8090: chip id: 0x8090
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:265
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: Using pmuio1-supply regulator from /i2c@fdd40000/pmic@20/regulators/LDO_REG6
rk808 rk8090: DEBUG of_regulator_get:211 reg:vcc6
rk808 rk8090: DEBUG of_regulator_get:217
rk808 rk8090: DEBUG of_regulator_get:231 prop:vcc6-supply
rk808 rk8090: DEBUG of_regulator_get:243
rk808 rk8090: DEBUG of_regulator_get:265
rk808 rk8090: Using vcc6-supply regulator from /vcc3v3-sys
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG reg:pmuio1 (0000000040090050) uV:3300000
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG rk_iodomain_probe:121 reg:pmuio2
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:211 reg:pmuio2
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:217
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:231 prop:pmuio2-supply
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:243
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:265
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: Using pmuio2-supply regulator from /i2c@fdd40000/pmic@20/regulators/LDO_REG6
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG reg:pmuio2 (0000000040090580) uV:3300000
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG rk_iodomain_probe:121 reg:vccio1
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:211 reg:vccio1
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:217
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:231 prop:vccio1-supply
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:243
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:265
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: Using vccio1-supply regulator from /i2c@fdd40000/pmic@20/regulators/LDO_REG4
rk808 rk8090: DEBUG of_regulator_get:211 reg:vcc5
rk808 rk8090: DEBUG of_regulator_get:217
rk808 rk8090: DEBUG of_regulator_get:231 prop:vcc5-supply
rk808 rk8090: DEBUG of_regulator_get:243
rk808 rk8090: DEBUG of_regulator_get:265
rk808 rk8090: Using vcc5-supply regulator from /vcc3v3-sys
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG reg:vccio1 (0000000040090da0) uV:900000
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG rk_iodomain_probe:121 reg:vccio2
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:211 reg:vccio2
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:217
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: No vccio2-supply node found, using dummy regulator
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:228 prop:vccio2-supply not found
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG rk_iodomain_probe:121 reg:vccio3
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:211 reg:vccio3
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:217
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:231 prop:vccio3-supply
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:243
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:265
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: Using vccio3-supply regulator from /i2c@fdd40000/pmic@20/regulators/LDO_REG5
rk808 rk8090: DEBUG of_regulator_get:211 reg:vcc6
rk808 rk8090: DEBUG of_regulator_get:217
rk808 rk8090: DEBUG of_regulator_get:231 prop:vcc6-supply
rk808 rk8090: DEBUG of_regulator_get:243
rk808 rk8090: DEBUG of_regulator_get:265
rk808 rk8090: Using vcc6-supply regulator from /vcc3v3-sys
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG reg:vccio3 (000000004007b908) uV:3300000
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG rk_iodomain_probe:121 reg:vccio4
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:211 reg:vccio4
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:217
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:231 prop:vccio4-supply
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:243
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:265
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: Using vccio4-supply regulator from /i2c@fdd40000/pmic@20/regulators/SWITCH_REG1
rk808 rk8090: DEBUG of_regulator_get:211 reg:vcc9
rk808 rk8090: DEBUG of_regulator_get:217
rk808 rk8090: DEBUG of_regulator_get:231 prop:vcc9-supply
rk808 rk8090: DEBUG of_regulator_get:243
rk808 rk8090: DEBUG of_regulator_get:265
rk808 rk8090: Using vcc9-supply regulator from /vcc3v3-sys
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG reg:vccio4 (0000000040079130) uV:-22
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG rk_iodomain_probe:121 reg:vccio5
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:211 reg:vccio5
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:217
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:231 prop:vccio5-supply
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:243
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:265
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: Using vccio5-supply regulator from /i2c@fdd40000/pmic@20/regulators/SWITCH_REG1
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG reg:vccio5 (0000000040079658) uV:-22
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG rk_iodomain_probe:121 reg:vccio6
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:211 reg:vccio6
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:217
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:231 prop:vccio6-supply
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:243
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:265
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: Using vccio6-supply regulator from /i2c@fdd40000/pmic@20/regulators/DCDC_REG5
rk808 rk8090: DEBUG of_regulator_get:211 reg:vcc7
rk808 rk8090: DEBUG of_regulator_get:217
rk808 rk8090: DEBUG of_regulator_get:231 prop:vcc7-supply
rk808 rk8090: DEBUG of_regulator_get:243
rk808 rk8090: DEBUG of_regulator_get:265
rk808 rk8090: Using vcc7-supply regulator from /vcc3v3-sys
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG reg:vccio6 (0000000040079e70) uV:1800000
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG rk_iodomain_probe:121 reg:vccio7
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:211 reg:vccio7
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:217
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:231 prop:vccio7-supply
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:243
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG of_regulator_get:265
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: Using vccio7-supply regulator from /i2c@fdd40000/pmic@20/regulators/SWITCH_REG1
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG reg:vccio7 (00000000400733c8) uV:-22
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG rk_iodomain_probe:143 ret:-19
ERROR: eqos-rockchip fe010000.ethernet@fe010000.of: offset 388 val: 7f7f2f3c (rx:2f,tx:3c)
mdio_bus: miibus0: probed
dw_mmc fe2b0000.mmc@fe2b0000.of: DEBUG of_regulator_get:211 reg:vmmc
dw_mmc fe2b0000.mmc@fe2b0000.of: DEBUG of_regulator_get:217
dw_mmc fe2b0000.mmc@fe2b0000.of: DEBUG of_regulator_get:231 prop:vmmc-supply
dw_mmc fe2b0000.mmc@fe2b0000.of: DEBUG of_regulator_get:243
dw_mmc fe2b0000.mmc@fe2b0000.of: DEBUG of_regulator_get:265
dw_mmc fe2b0000.mmc@fe2b0000.of: Using vmmc-supply regulator from /i2c@fdd40000/pmic@20/regulators/SWITCH_REG2
rk808 rk8090: DEBUG of_regulator_get:211 reg:vcc8
rk808 rk8090: DEBUG of_regulator_get:217
rk808 rk8090: DEBUG of_regulator_get:231 prop:vcc8-supply
rk808 rk8090: DEBUG of_regulator_get:243
rk808 rk8090: DEBUG of_regulator_get:265
rk808 rk8090: Using vcc8-supply regulator from /vcc3v3-sys
dw_mmc fe2b0000.mmc@fe2b0000.of: registered as sd
sd: detected SD card version 1.0
sd: registered sd
rk3568-dwcmshc-sdhci fe310000.mmc@fe310000.of: DEBUG of_regulator_get:211 reg:vmmc
rk3568-dwcmshc-sdhci fe310000.mmc@fe310000.of: DEBUG of_regulator_get:217
rk3568-dwcmshc-sdhci fe310000.mmc@fe310000.of: No vmmc-supply node found, using dummy regulator
rk3568-dwcmshc-sdhci fe310000.mmc@fe310000.of: DEBUG of_regulator_get:228 prop:vmmc-supply not found
rk3568-dwcmshc-sdhci fe310000.mmc@fe310000.of: registered as emmc
emmc: detected MMC card version 5.1
emmc: registered emmc.boot0
emmc: registered emmc.boot1
emmc: registered emmc
rockchip_saradc fe720000.saradc@fe720000.of: DEBUG of_regulator_get:211 reg:vref
rockchip_saradc fe720000.saradc@fe720000.of: DEBUG of_regulator_get:217
rockchip_saradc fe720000.saradc@fe720000.of: DEBUG of_regulator_get:231 prop:vref-supply
rockchip_saradc fe720000.saradc@fe720000.of: DEBUG of_regulator_get:243
rockchip_saradc fe720000.saradc@fe720000.of: DEBUG of_regulator_get:265
rockchip_saradc fe720000.saradc@fe720000.of: Using vref-supply regulator from /i2c@fdd40000/pmic@20/regulators/LDO_REG7
rk808 rk8090: DEBUG of_regulator_get:211 reg:vcc6
rk808 rk8090: DEBUG of_regulator_get:217
rk808 rk8090: DEBUG of_regulator_get:231 prop:vcc6-supply
rk808 rk8090: DEBUG of_regulator_get:243
rk808 rk8090: DEBUG of_regulator_get:265
rk808 rk8090: Using vcc6-supply regulator from /vcc3v3-sys