iodomain: disable some debug
voltages look good now, but usb seems broken

BPI-R2PRO> fatload mmc 1:2 ${kernel_addr_r} barebox-dt-2nd_iodomain.img
421775 bytes read in 42 ms (9.6 MiB/s)
BPI-R2PRO> fatload mmc 1:2 ${fdt_addr_r} barebox-r2pro.dtb
36201 bytes read in 8 ms (4.3 MiB/s)
BPI-R2PRO> booti ${kernel_addr_r} - ${fdt_addr_r}
Flattened Device Tree blob at 0a100000
   Booting using the fdt blob at 0xa100000
   Loading Device Tree to 000000007df33000, end 000000007df3ed68 ... OK

Starting kernel ...

Deep probe supported due to rockchip,rk3568-bpi-r2pro
Switch to console [cs0]

barebox 2022.06.0-00241-gbfefa5d6e70c-dirty #168 Sun Jul 24 11:35:11 CEST 2022

Board: Bananapi-R2 Pro (RK3568) DDR4 Board
Deep probe supported due to rockchip,rk3568-bpi-r2pro
netconsole: registered as netconsole-1
psci psci.of: detected version 1.1
xHCI xHCI0: USB XHCI 1.10
xHCI xHCI1: USB XHCI 1.10
ERROR: usb@fd800000: Failed to get clk index: 3 ret: Requested probe deferral
ERROR: ehci fd800000.usb@fd800000.of: probe deferred
ERROR: usb@fd880000: Failed to get clk index: 3 ret: Requested probe deferral
ERROR: ehci fd880000.usb@fd880000.of: probe deferred
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG rk_iodomain_probe:121 reg:pmuio1
rk808 rk8090: chip id: 0x8090
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG reg:pmuio1 (00000000400927a0) uV:3300000
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG rk_iodomain_probe:121 reg:pmuio2
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG reg:pmuio2 (0000000040092960) uV:3300000
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG rk_iodomain_probe:121 reg:vccio1
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG reg:vccio1 (0000000040092ad0) uV:900000
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG rk_iodomain_probe:121 reg:vccio2
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG rk_iodomain_probe:121 reg:vccio3
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG reg:vccio3 (0000000040092d08) uV:3300000
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG rk_iodomain_probe:121 reg:vccio4
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG reg:vccio4 (0000000040092e78) uV:3300000
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG rk_iodomain_probe:121 reg:vccio5
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG reg:vccio5 (0000000040090008) uV:3300000
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG rk_iodomain_probe:121 reg:vccio6
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG reg:vccio6 (0000000040090178) uV:1800000
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG rk_iodomain_probe:121 reg:vccio7
rk_iodomain fdc20000.syscon@fdc20000:io-domains.of: DEBUG reg:vccio7 (00000000400902e8) uV:3300000
ERROR: eqos-rockchip fe010000.ethernet@fe010000.of: offset 388 val: 7f7f2f3c (rx:2f,tx:3c)
mdio_bus: miibus0: probed
dw_mmc fe2b0000.mmc@fe2b0000.of: registered as sd
sd: detected SD card version 1.0
sd: registered sd
rk3568-dwcmshc-sdhci fe310000.mmc@fe310000.of: registered as emmc
emmc: detected MMC card version 5.1
emmc: registered emmc.boot0
emmc: registered emmc.boot1
emmc: registered emmc
rockchip_saradc fe720000.saradc@fe720000.of: registered as aiodev0
malloc space: 0x3fffb800 -> 0x7fdf6fff (size 1022 MiB)
ERROR: usb@fd880000: Failed to get clk index: 3 ret: Requested probe deferral
ERROR: ehci fd880000.usb@fd880000.of: probe deferred
ERROR: usb@fd800000: Failed to get clk index: 3 ret: Requested probe deferral
ERROR: ehci fd800000.usb@fd800000.of: probe deferred
ERROR: fd800000.usb@fd800000.of: probe permanently deferred
ERROR: fd880000.usb@fd880000.of: probe permanently deferred
rk3568-r2pro: hwid_voltage: 3300
rk3568-r2pro: Detected RK3568 BananaPi R2 Pro unknown
rk3568-r2pro: temp_voltage: 3300
envfs: no envfs (magic mismatch) - envfs never written?

Hit m for menu or any to stop autoboot:    3
barebox@BPI R2PRO:/